name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Pull Code
        uses: actions/checkout@v7

      - name: Setup go and dependencies
        uses: actions/setup-go@v7
        with:
          go-version: 'stable'
          check-latest: true
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m --build-tags="testcontainers,realmongo"

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Pull Code
        uses: actions/checkout@v7

      - name: Setup go and dependencies
        uses: actions/setup-go@v7
        with:
          go-version: 'stable'
          check-latest: true
          cache: true

      - name: Verify module dependencies
        run: |
          go mod verify
          git diff --exit-code go.mod go.sum || (echo "go.mod/go.sum dirty" && exit 1)

      - name: Run unit tests
        run: go test -race -v ./...

      - name: Run Testcontainers integration tests
        run: go test -race -v -tags=testcontainers ./...

      - name: Run real Mongo integration tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: go test -race -v -tags=realmongo ./...

      - name: Run tests with race detector and coverage
        run: go test -race -tags="testcontainers,realmongo" -coverprofile=coverage.out ./...

      - name: Verify package compilation
        run: go build -v ./...

