name: DEPLOY.yml
on:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'
permissions:
  id-token: write # Required for requesting the JWT/OIDC token
  contents: read  # Required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Pull Code
        uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Short SHA
        id: SHORT_SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Replace Parameter in cloudbuild.yaml
        run: |
          sed -i 's/_IMAGE_NAME_/${{ vars.IMAGE_NAME }}/g' cloudbuild.yaml
          sed -i 's/_SHORT_SHA_/${{ env.SHORT_SHA }}/g' cloudbuild.yaml
          sed -i 's/_BUILDER_/${{ vars.BUILDER }}/g' cloudbuild.yaml
          sed -i 's/_SERVICE_NAME_/${{ vars.SERVICE_NAME }}/g' cloudbuild.yaml
          sed -i 's/_SERVICE_ACCOUNT_/${{ secrets.SERVICE_ACCOUNT }}/g' cloudbuild.yaml
          sed -i 's/_LOCATION_/${{ vars.LOCATION }}/g' cloudbuild.yaml
          sed -i 's/_REPO_NAME_/${{ vars.REPO_NAME }}/g' cloudbuild.yaml

      - name: Submit Cloud Build
        run: |
          gcloud builds submit